#define LEX_UNUSED 0
#define LEX_INT_DECL 1
#define LEX_LBRACK 2
#define LEX_RBRACK 3
#define LEX_COMMA 4
#define LEX_SEMICOLON 5
#define LEX_IF 6
#define LEX_ELSE 7
#define LEX_WHILE 8
#define LEX_FOR 9
#define LEX_INT 10
#define LEX_EXIT 11
#define LEX_READ 12
#define LEX_LPAREN 13
#define LEX_RPAREN 14
#define LEX_PROGRAM 15
#define LEX_PRINT 16
#define LEX_ASSIGN 17
#define LEX_PLEQ 18
#define LEX_MINEQ 19
#define LEX_MULEQ 20
#define LEX_DIVEQ 21
#define LEX_MUL 22
#define LEX_DIV 23
#define LEX_PLUS 24
#define LEX_MIN 25
#define LEX_LT 26
#define LEX_GT 27
#define LEX_LEQ 28
#define LEX_GEQ 29
#define LEX_EQ 30
#define LEX_NEQ 31
#define LEX_AND 32
#define LEX_OR 33
#define LEX_ESC 34
#define LEX_HEX 35
#define LEX_IDENT 36
#define LEX_NUM 37
#define LEX_NEWLINE 38
#define LEX_EOF 39
#define LEX_STRING 40
#define NUM_TOKENS 41

char* tokens_names[42];
