#define LEX_UNUSED 0
#define LEX_INT_DECL 1
#define LEX_LBRACK 2
#define LEX_RBRACK 3
#define LEX_COMMA 4
#define LEX_DOT 5
#define LEX_SEMICOLON 6
#define LEX_IF 7
#define LEX_ELSE 8
#define LEX_WHILE 9
#define LEX_FOR 10
#define LEX_INT 11
#define LEX_EXIT 12
#define LEX_READ 13
#define LEX_LPAREN 14
#define LEX_RPAREN 15
#define LEX_PROGRAM 16
#define LEX_PRINT 17
#define LEX_ASSIGN 18
#define LEX_PLEQ 19
#define LEX_MINEQ 20
#define LEX_MULEQ 21
#define LEX_DIVEQ 22
#define LEX_MUL 23
#define LEX_DIV 24
#define LEX_PLUS 25
#define LEX_MIN 26
#define LEX_LT 27
#define LEX_GT 28
#define LEX_LEQ 29
#define LEX_GEQ 30
#define LEX_EQ 31
#define LEX_NEQ 32
#define LEX_AND 33
#define LEX_OR 34
#define LEX_ESC 35
#define LEX_HEX 36
#define LEX_IDENT 37
#define LEX_NUM 38
#define LEX_NEWLINE 39
#define LEX_EOF 40
#define LEX_STRING 41
#define LEX_CHAR 42
#define LEX_CHARDEC 43
#define LEX_STRDEC 44
#define LEX_STRUCT 45
#define LEX_FUNC 46
#define LEX_CALL 47
#define LEX_COLON 48
#define LEX_RETURN 49
#define NUM_TOKENS 50

char* tokens_names[51];
